# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
	config.vm.define :app do |app_config|
		app_config.vm.box = "base"
		app_config.vm.network :hostonly, "10.0.0.2"
		app_config.vm.network :bridged
		app_config.vm.forward_port 80, 8081
		app_config.vm.share_folder "app_data","/app","app_files"
	end
	config.vm.define :db do |db_config|
		db_config.vm.box = "base"
		db_config.vm.network :hostonly, "10.0.0.3"
		db_config.vm.share_folder "db_data","/var/db/db_files","db_files"
	end
	config.vm.define :static do |static_config|
		static_config.vm.box = "base"
		static_config.vm.network :hostonly, "10.0.0.4"
		static_config.vm.share_folder "static_data","/var/www/static","static_files"
	end
end
